create or replace view EDG.MODEL.HILLOFTOWIE_WEATHER_MONTHLY(
	MONTH,
	AVG_WINDSPEED_10M,
	AVG_WINDSPEED_CUBED
) as
SELECT 
  TO_CHAR(DATETIME, 'YYYY-MM') AS MONTH,
  ROUND(AVG(WINDSPEED_10M), 3) AS AVG_WINDSPEED_10M,
  ROUND(AVG(POWER(WINDSPEED_10M, 3)), 3) AS AVG_WINDSPEED_CUBED
FROM EDG.PREP.HILLOFTOWIE_WEATHER
GROUP BY TO_CHAR(DATETIME, 'YYYY-MM')
ORDER BY MONTH;