create or replace view EDG.MODEL.TURBINES_TOTAL_OUTPUT_BY_MONTH(
	MONTH_NUMBER,
	MONTH,
	NUMBER_OF_TURBINES,
	TOTAL_ENERGY_PRODUCED_GWH
) as
SELECT 
    MONTH("TIMESTAMP") AS MONTH_NUMBER,
    TO_CHAR("TIMESTAMP", 'MMMM') AS MONTH,
    COUNT(DISTINCT "STATIONID") AS NUMBER_OF_TURBINES, 
    ROUND(SUM("ENERGYTOT") / 1000000000.0) AS TOTAL_ENERGY_PRODUCED_GWH
FROM EDG.PREP.TURBINES_DAILY_SUMMARY_2024_FINAL
GROUP BY MONTH("TIMESTAMP"), TO_CHAR("TIMESTAMP", 'MMMM')
ORDER BY MONTH_NUMBER;