create or replace view EDG.MODEL.TURBINES_TOTAL_OUTPUT_BY_TURBINE(
	STATIONID,
	TOTAL_ENERGY_PRODUCED_MWH,
	TOTAL_ENERGY_MONTHLY_MEAN_MWH,
	TOTAL_ENERGY_PRODUCED_GWH,
	TOTAL_ENERGY_MONTHLY_MEAN_GWH
) as
SELECT 
    STATIONID,
    ROUND(SUM("ENERGYTOT") / 1000000.0) AS TOTAL_ENERGY_PRODUCED_MWH,
    ROUND(TOTAL_ENERGY_PRODUCED_MWH / 12.0) AS TOTAL_ENERGY_MONTHLY_MEAN_MWH,
    ROUND(SUM("ENERGYTOT") / 1000000000.0) AS TOTAL_ENERGY_PRODUCED_GWH,
    ROUND(TOTAL_ENERGY_PRODUCED_GWH / 12.0) AS TOTAL_ENERGY_MONTHLY_MEAN_GWH
FROM EDG.PREP.TURBINES_DAILY_SUMMARY_2024_FINAL
GROUP BY STATIONID
HAVING SUM(ENERGYTOT) IS NOT NULL
ORDER BY TOTAL_ENERGY_PRODUCED_GWH DESC;