create or replace view EDG.MODEL.VW_AVG_MONTHLY_WINDSPEED(
	LOCATION,
	YEAR,
	MONTH,
	AVG_WINDSPEED_10M
) as
SELECT
    LOCATION,
    YEAR(DATETIME) AS year,
    MONTH(DATETIME) AS month,
    ROUND(AVG(WINDSPEED_10M), 2) AS avg_windspeed_10m
FROM PREP.SCOTLAND_WEATHER_DATA
GROUP BY LOCATION, YEAR(DATETIME), MONTH(DATETIME)
ORDER BY LOCATION, year, month;