create or replace view EDG.MODEL.VW_LOCATION_SUMMARY(
	LOCATION,
	NUM_RECORDS,
	AVG_WINDSPEED,
	MAX_WINDSPEED,
	MIN_WINDSPEED
) as
SELECT
    LOCATION,
    COUNT(*) AS num_records,
    ROUND(AVG(WINDSPEED_10M), 2) AS avg_windspeed,
    ROUND(MAX(WINDSPEED_10M), 2) AS max_windspeed,
    ROUND(MIN(WINDSPEED_10M), 2) AS min_windspeed
FROM PREP.SCOTLAND_WEATHER_DATA
GROUP BY LOCATION
ORDER BY LOCATION;