create or replace view EDG.MODEL.VW_TURBINE_STOP_CAUSES(
	DATE,
	STATIONGROUPID,
	TURBINE_FAULTS,
	GRID_FAULTS,
	ENVIRONMENTAL_STOPS,
	COMMANDED_STOPS
) as
SELECT 
  TIMESTAMP AS date,
  STATIONGROUPID,
  SUM(STOPSTURBINEFAULTTOT) AS turbine_faults,
  SUM(STOPSGRIDFAULTTOT) AS grid_faults,
  SUM(STOPSENVIRONMENTALTOT) AS environmental_stops,
  SUM(STOPSCOMMANDEDTOT) AS commanded_stops
FROM EDG.PREP.TURBINES_DAILY_SUMMARY_2024_NON_NULL_COLS
GROUP BY TIMESTAMP, STATIONGROUPID;