create or replace view EDG.MODEL.WIND_DIRECTION_SUMMARY(
	MONTH_NUMBER,
	MONTH,
	WIND_DIRECTION_LABEL,
	OCCURRENCES
) as
SELECT 
MONTH (DATETIME) AS Month_Number,
  TO_CHAR("DATETIME", 'MMMM') AS MONTH,
  WIND_DIRECTION_LABEL,
  COUNT(*) AS OCCURRENCES
FROM (
  SELECT 
    DATETIME,
    CASE
      WHEN AVG_WINDDIRECTION_10M BETWEEN 0 AND 22.5 THEN 'N'
      WHEN AVG_WINDDIRECTION_10M BETWEEN 22.5 AND 67.5 THEN 'NE'
      WHEN AVG_WINDDIRECTION_10M BETWEEN 67.5 AND 112.5 THEN 'E'
      WHEN AVG_WINDDIRECTION_10M BETWEEN 112.5 AND 157.5 THEN 'SE'
      WHEN AVG_WINDDIRECTION_10M BETWEEN 157.5 AND 202.5 THEN 'S'
      WHEN AVG_WINDDIRECTION_10M BETWEEN 202.5 AND 247.5 THEN 'SW'
      WHEN AVG_WINDDIRECTION_10M BETWEEN 247.5 AND 292.5 THEN 'W'
      WHEN AVG_WINDDIRECTION_10M BETWEEN 292.5 AND 337.5 THEN 'NW'
      WHEN AVG_WINDDIRECTION_10M > 337.5 OR AVG_WINDDIRECTION_10M < 0 THEN 'N'
    END AS WIND_DIRECTION_LABEL
  FROM EDG.PREP.HILLOFTOWIE_WEATHER_AVG
)
GROUP BY Month, MONTH_Number, WIND_DIRECTION_LABEL
ORDER BY Month_number, WIND_DIRECTION_LABEL;