create or replace view EDG.MODEL.WIND_SPEED_MEAN_BY_DAY(
	TIMESTAMP,
	MEAN_WIND_SPEED
) as
SELECT 
    TIMESTAMP,
    AVG(WINDSPEEDMEANTOT) AS MEAN_WIND_SPEED
FROM EDG.PREP.TURBINES_DAILY_SUMMARY_2024_FINAL
GROUP BY TIMESTAMP
ORDER BY TIMESTAMP ASC;