create or replace view EDG.PREP.HILLOFTOWIE_WEATHER_AVG(
	DATETIME,
	AVG_WINDSPEED_10M,
	AVG_WINDDIRECTION_10M
) as
SELECT 
  DATETIME,
  ROUND(AVG(WINDSPEED_10M), 3) AS AVG_WINDSPEED_10M,
  ROUND(AVG(WINDDIRECTION_10M), 3) AS AVG_WINDDIRECTION_10M
FROM EDG.PREP.HILLOFTOWIE_WEATHER
GROUP BY DATETIME
ORDER BY DATETIME;