create or replace view EDG.MODEL.VW_INVERNESS_VS_ABERDEEN_MONTHLY(
	LOCATION,
	YEAR,
	MONTH,
	AVG_MONTHLY_WINDSPEED
) as
SELECT
    LOCATION,
    YEAR(DATETIME) AS year,
    MONTH(DATETIME) AS month,
    ROUND(AVG(WINDSPEED_10M), 2) AS avg_monthly_windspeed
FROM PREP.SCOTLAND_WEATHER_DATA
WHERE LOCATION IN ('Inverness', 'Aberdeen')
GROUP BY LOCATION, YEAR(DATETIME), MONTH(DATETIME)
ORDER BY year, month, LOCATION;