create or replace view EDG.MODEL.VW_INVERNESS_VS_ABERDEEN_WINDSPEED(
	LOCATION,
	AVG_WINDSPEED
) as
SELECT
    LOCATION,
    ROUND(AVG(WINDSPEED_10M), 2) AS avg_windspeed
FROM PREP.SCOTLAND_WEATHER_DATA
WHERE LOCATION IN ('Inverness', 'Aberdeen')
GROUP BY LOCATION
ORDER BY avg_windspeed DESC;