create or replace view EDG.MODEL.VW_TURBINE_AVAILABILITY_TRENDS(
	DATE,
	STATIONGROUPID,
	AVG_AVAILABILITY,
	AVG_CAPACITY_FACTOR
) as
SELECT 
  TIMESTAMP AS date,
  STATIONGROUPID,
  AVG(AVAILABILITY2) AS avg_availability,
  AVG(CAPACITYFACTOR) AS avg_capacity_factor
FROM EDG.PREP.TURBINES_DAILY_SUMMARY_2024_NON_NULL_COLS
GROUP BY TIMESTAMP, STATIONGROUPID;