CREATE OR REPLACE PROCEDURE EDG.PREP.TURBINES_CLEANUP_02_DEDUPLICATE_TIMESTAMPS()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS '   
BEGIN
    --   This view removes duplicate records from the TURBINES_DAILY_SUMMARY_2024_NON_NULL_COLS
    --   table based on the combination of STATIONID and TIMESTAMP.
    CREATE OR REPLACE TABLE EDG.PREP.TURBINES_DAILY_SUMMARY_2024_NO_DUPLICATES AS
    WITH LABELED_ROWS AS (
        SELECT 
            ROW_NUMBER() OVER (PARTITION BY STATIONID, TIMESTAMP ORDER BY STATIONID, TIMESTAMP) AS ROW_NUM,
            *
        FROM EDG.PREP.TURBINES_DAILY_SUMMARY_2024_NON_NULL_COLS
    )
    SELECT * EXCLUDE (ROW_NUM)
    FROM LABELED_ROWS
    WHERE ROW_NUM = 1;
END;
';