CREATE OR REPLACE PROCEDURE EDG.PREP.TURBINES_CLEANUP_03_REMOVE_SEPTEMBER()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS '   
BEGIN
    -- Remove September data from the turbines daily summary table
    -- This is necessary because the September data only contains 1 day of data
    CREATE OR REPLACE TABLE EDG.PREP.TURBINES_DAILY_SUMMARY_2024_NO_SEPTEMBER AS
    SELECT *
    FROM EDG.PREP.TURBINES_DAILY_SUMMARY_2024_NO_DUPLICATES
    WHERE MONTH(TIMESTAMP) != 9;
END;
';