CREATE OR REPLACE PROCEDURE EDG.PREP.TURBINES_CLEANUP_ALL()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS '
BEGIN
    CALL EDG.PREP.TURBINES_CLEANUP_01_CREATE_TABLE_NON_NULL_COLUMNS(''TURBINES_DAILY_SUMMARY_2024'');
    CALL EDG.PREP.TURBINES_CLEANUP_02_DEDUPLICATE_TIMESTAMPS();
    CALL EDG.PREP.TURBINES_CLEANUP_03_REMOVE_SEPTEMBER();
    CALL EDG.PREP.TURBINES_CLEANUP_04_CREATE_FINAL_VIEW();
    RETURN ''All cleanup procedures completed successfully'';
END;
';