CREATE OR REPLACE PROCEDURE EDG.PREP.TURBINES_CLEANUP_04_CREATE_FINAL_VIEW()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS '   
BEGIN
    CREATE OR REPLACE VIEW EDG.PREP.TURBINES_DAILY_SUMMARY_2024_FINAL AS
    SELECT *
    FROM EDG.PREP.TURBINES_DAILY_SUMMARY_2024_NO_SEPTEMBER;
END;
';